{{- if .Values.mongo.enabled }}
apiVersion: v1
kind: Service
metadata:
  # unique per release+chart (avoids collision)
  name: {{ .Release.Name }}-{{ .Chart.Name }}-mongo
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: mongo
spec:
  type: ClusterIP
  ports:
    - name: mongo
      port: {{ .Values.mongo.servicePort }}
      targetPort: {{ .Values.mongo.servicePort }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: mongo
{{- end }}
