apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: tasks-service
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
      name: http
