{{- if .Values.mongo.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-mongo
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: mongo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/component: mongo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/component: mongo
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.image }}
          ports:
            - containerPort: {{ .Values.mongo.servicePort }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongo.auth.rootUser | quote }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongo.auth.rootPassword | quote }}
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongo.auth.database | quote }}
          {{- if .Values.mongo.persistence.enabled }}
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          {{- end }}
          resources:
{{ toYaml .Values.mongo.resources | indent 12 }}
      {{- if .Values.mongo.persistence.enabled }}
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ .Chart.Name }}-mongo-pvc
      {{- end }}
---
{{- if .Values.mongo.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-mongo-pvc
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: mongo
spec:
  accessModes: {{ toYaml .Values.mongo.persistence.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.mongo.persistence.size }}
  {{- if .Values.mongo.persistence.storageClassName }}
  storageClassName: {{ .Values.mongo.persistence.storageClassName }}
  {{- end }}
{{- end }}
{{- end }}
