apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: users-service
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
