apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-mongo-pvc
  namespace: devops-dashboard
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasks-mongo-pvc
  namespace: devops-dashboard
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
